### ISSUE TITLE
Fatal Error! "Failed to execute script runMOSAIC" on windows platform

### ISSUE THREAD

**Issue by zixuanweeei** [usnistgov/mosaic#100]
![image](https://user-images.githubusercontent.com/9527221/43527019-25a4a088-95d8-11e8-90ed-348996ddc261.png)
I alse run it with admin mode, but it still doesn't work. My windows version number is 1803.

**Comment by zixuanweeei** [comment]
@abalijepalli Hi, i am running the latest version V1.3.6.

**Comment by abalijepalli** [comment]
I would recommend temporarily downgrading to v1.3.5 (https://github.com/usnistgov/mosaic/releases/download/v1.3.5/mosaic-x64-1.3.5.801e7e5.zip) while we look at this issue.

**Comment by zixuanweeei** [comment]
Thanks. But it still dosen't work, while it worked on the last Windows version. It may be not compatible with the latest Windows version. Besides, I recognise that the MOSAIC is written in Python 2.x, while a Anaconda's Python 3.5 release is installed on my PC. Any confliction there between them?

**Comment by abalijepalli** [comment]
Are you running the prebuilt executable or installing MOSAIC from the source code? If installing from source you will need the Anaconda python 2.7 installer since MOSAIC is written in Python 2.7. You can download it here: https://www.anaconda.com/download/#windows.

**Comment by zixuanweeei** [comment]
I am running the prebuilt executble MOSAIC, not the source.

**Comment by abalijepalli** [comment]
If you are using the pre-built executable, you shouldn't need Anaconda.

I tested v1.3.6 on Windows 7 and was able to reproduce the issue you report. 

However, v1.3.5 works fine. I don't have a Windows 10 installation so I can't test on that version. If v1.3.5 doesn't work for you, you could install from source.
