### ISSUE TITLE
analysisObj.Run()  TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by N-damo** [usnistgov/mosaic#106]
import mosaic.trajio.abfTrajIO  as abf
import mosaic.apps.SingleChannelAnalysis as SingleChannelAnalysis
import mosaic.partition.eventSegment as es
import mosaic.process.adept2State as adept2State
import mosaic.filters.besselLowpassFilter as bessel
analysisObj=SingleChannelAnalysis.SingleChannelAnalysis('./', abf.abf, bessel.besselLowpassFilter, es.eventSegment, adept2State.adept2State)
analysisObj.Run()

error:
TypeError: 'module' object is not callable

mosai version 2.0
i follow the document,but not work. https://pages.nist.gov/mosaic//html/doc/ScriptingandAdvancedFeatures.html

**Comment by abalijepalli** [comment]
Within your `analysisObj` declaration, `abf.abf` should be replaced with `abf.abfTrajiO`. The complete declaration should be: 

```
analysisObj=SingleChannelAnalysis.SingleChannelAnalysis(
'./', 
abf.abfTrajIO, 
bessel.besselLowpassFilter, 
es.eventSegment, 
adept2State.adept2State
)
```

Also, note that `besselLowpassFilter` is a bit unstable. If you don't need filtering, replace it with `None.`
