### ISSUE TITLE
Mosaic.exe can not be executed in WIN1064

### ISSUE THREAD

**Issue by mliyuanjie** [usnistgov/mosaic#108]
I download the latest version for win10 64bit. When I unzip and click the mosaic.exe, there is not any response.

**Comment by mliyuanjie** [comment]
good, I forgot it is a webui. Thank you very much.

**Comment by abalijepalli** [comment]
It's actually a bug -- the browser should launch automatically. We'll fix it in the next release.

**Comment by abalijepalli** [comment]
Resolved with commit 5e251c233efff74b6e935511cb50ffd5dd094ccb.
