### ISSUE TITLE
Can not open in macOS 12.0.1 with apple m1 pro 

### ISSUE THREAD

**Issue by LynneHomels** [usnistgov/mosaic#110]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Translated Report (Full Report Below)
-------------------------------------

Process:               MOSAIC [9856]
Path:                  /Applications/MOSAIC.app/Contents/MacOS/MOSAIC
Identifier:            MOSAIC
Version:               1.3.6 (???)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2021-12-06 10:44:02.3937 +0800
OS Version:            macOS 12.0.1 (21A559)
Report Version:        12
Anonymous UUID:        8E4955EF-B107-0CB6-643D-06BB10BBA547

Sleep/Wake UUID:       5B89FCF5-94C7-4F97-B7A8-C64820B92F7B

Time Awake Since Boot: 8200 seconds
Time Since Wake:       2349 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 4 Illegal instruction: 4
Terminating Process:   exc handler [9856]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   QtCore                        	       0x112b52fa2 normalizeTypeInternal(char const*, char const*, bool, bool) + 792
1   QtCore                        	       0x112b5036b qNormalizeType(char*, int&, QByteArray&) + 146
2   QtCore                        	       0x112b5017b QMetaObject::normalizedType(char const*) + 211
3   QtCore                        	       0x112b53d45 QMetaType::registerType(char const*, void (*)(void*), void* (*)(void const*)) + 93
4   PyQt4.QtCore.so               	       0x1121ab3f6 int qRegisterMetaType<PyQt_PyObject>(char const*, PyQt_PyObject*) + 47
5   PyQt4.QtCore.so               	       0x1121ab253 qpycore_post_init(_object*) + 291
6   .Python                       	       0x110fc1758 _PyImport_LoadDynamicModule + 140
7   .Python                       	       0x110fc11ef imp_load_module + 243
8   .Python                       	       0x110fac53a PyEval_EvalFrameEx + 27019
9   .Python                       	       0x110fa59bf PyEval_EvalCodeEx + 1618
10  .Python                       	       0x110f4b088 function_call + 350
11  .Python                       	       0x110f2ce95 PyObject_Call + 99
12  .Python                       	       0x110f37b67 instancemethod_call + 173
13  .Python                       	       0x110f2ce95 PyObject_Call + 99
14  .Python                       	       0x110f2d023 call_function_tail + 72
15  .Python                       	       0x110f2d21c PyObject_CallMethod + 231
16  .Python                       	       0x110fc0454 import_submodule + 267
17  .Python                       	       0x110fc0028 load_next + 280
18  .Python                       	       0x110fbf240 PyImport_ImportModuleLevel + 1185
19  .Python                       	       0x110fa0fbd builtin___import__ + 135
20  .Python                       	       0x110f2ce95 PyObject_Call + 99
21  .Python                       	       0x110fafb2b PyEval_CallObjectWithKeywords + 165
22  .Python                       	       0x110faace3 PyEval_EvalFrameEx + 20788
23  .Python                       	       0x110fa59bf PyEval_EvalCodeEx + 1618
24  .Python                       	       0x110fa5367 PyEval_EvalCode + 48
25  MOSAIC                        	       0x104b7f0c9 0x104b7d000 + 8393
26  MOSAIC                        	       0x104b7f69a 0x104b7d000 + 9882
27  MOSAIC                        	       0x104b7dec4 0x104b7d000 + 3780

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffca08e4 0x7ff7ffc9c000 + 18660
1   runtime                       	    0x7ff7ffcad928 0x7ff7ffc9c000 + 71976
2   runtime                       	    0x7ff7ffcaf0a4 0x7ff7ffc9c000 + 77988

Thread 2:
0   runtime                       	    0x7ff7ffcbe814 0x7ff7ffc9c000 + 141332

Thread 3:
0   runtime                       	    0x7ff7ffcbe814 0x7ff7ffc9c000 + 141332

Thread 4:
0   runtime                       	    0x7ff7ffcbe814 0x7ff7ffc9c000 + 141332

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000025  rbx: 0x000000030e6cee18  rcx: 0x0000000000000000  rdx: 0x0000000000000008
  rdi: 0x0000000112be525b  rsi: 0x000000030e6cee18  rbp: 0x000000030e6cedb0  rsp: 0x000000030e6cece0
   r8: 0x0000000000000050   r9: 0x0000000000000074  r10: 0x00007ff854192b68  r11: 0x0000000110fdb238
  r12: 0x000000030e6cee25  r13: 0x000000000000000d  r14: 0x0000000112cc7a68  r15: 0x000000030e6cee18
  rip: 0x0000000112b52fa2  rfl: 0x0000000000000203
 tmp0: 0x0000000112b52fa2 tmp1: 0x4429fcc5c057fcc5 tmp2: 0x00244429fcc56024

Binary Images:
       0x112a47000 -        0x112cbdfff QtCore (*) <2878eedc-9ce1-3944-9514-c858d0d82326> /Applications/MOSAIC.app/Contents/MacOS/QtCore
       0x1121a9000 -        0x1122fefff PyQt4.QtCore.so (*) <5b5264e0-aac9-338d-be10-a6843cf0893a> /Applications/MOSAIC.app/Contents/MacOS/PyQt4.QtCore.so
       0x110f22000 -        0x111017fff .Python (*) <9a53817f-2101-3965-9831-1db81d851fba> /Applications/MOSAIC.app/Contents/MacOS/.Python
       0x104b7d000 -        0x104b83fff MOSAIC (1.3.6) <32ab4b3f-56df-3c81-b3ee-2215ac410955> /Applications/MOSAIC.app/Contents/MacOS/MOSAIC
    0x7ff7ffc9c000 -     0x7ff7ffccbfff runtime (*) <9f5d65be-d8d0-3979-bb05-e651a67e785c> /usr/libexec/rosetta/runtime

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=882.7M resident=0K(0%) swapped_out_or_unallocated=882.7M(100%)
Writable regions: Total=1.2G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.2G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
Kernel Alloc Once                    8K        1 
MALLOC                           206.1M       24 
MALLOC guard page                   96K        4 
MALLOC_MEDIUM (reserved)         480.0M        4         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
Rosetta Arena                     4096K        2 
Rosetta Generic                   1008K      249 
Rosetta IndirectBranch             192K        2 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack                80K        8 
Rosetta Thread Context              80K        8 
STACK GUARD                         12K        3 
Stack                             9772K        4 
Stack Guard                       56.0M        1 
VM_ALLOCATE                       17.3M       65 
__DATA                            15.5M      273 
__DATA_CONST                      8557K      144 
__DATA_DIRTY                       310K       80 
__FONT_DATA                          4K        1 
__LINKEDIT                       708.5M       44 
__OBJC_RO                         81.6M        1 
__OBJC_RW                         3120K        2 
__TEXT                           174.2M      283 
__UNICODE                          588K        1 
dyld private memory               1024K        1 
mapped file                        5.0G      400 
shared memory                      800K       12 
unshared pmap                     2288K        2 
===========                     =======  ======= 
TOTAL                              7.3G     1622 
TOTAL, minus reserved VM space     6.4G     1622 

-----------
Full Report
-----------

{"app_name":"MOSAIC","timestamp":"2021-12-06 10:44:02.00 +0800","app_version":"1.3.6","slice_uuid":"32ab4b3f-56df-3c81-b3ee-2215ac410955","build_version":"","platform":1,"bundleID":"MOSAIC","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.0.1 (21A559)","incident_id":"08224E31-8B54-4213-A734-8F9D485450F4","name":"MOSAIC"}
{
  "uptime" : 8200,
  "procLaunch" : "2021-12-06 10:43:59.0635 +0800",
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,3",
  "procStartAbsTime" : 198972714395,
  "coalitionID" : 3407,
  "osVersion" : {
    "train" : "macOS 12.0.1",
    "build" : "21A559",
    "releaseType" : "User"
  },
  "captureTime" : "2021-12-06 10:44:02.3937 +0800",
  "incident" : "08224E31-8B54-4213-A734-8F9D485450F4",
  "bug_type" : "309",
  "pid" : 9856,
  "procExitAbsTime" : 199052504602,
  "translated" : true,
  "cpuType" : "X86-64",
  "procName" : "MOSAIC",
  "procPath" : "\/Applications\/MOSAIC.app\/Contents\/MacOS\/MOSAIC",
  "bundleInfo" : {"CFBundleShortVersionString":"1.3.6","CFBundleIdentifier":"MOSAIC"},
  "storeInfo" : {"deviceIdentifierForVendor":"4D5B1118-C44A-55D9-8478-D1C175106F8F","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "MOSAIC",
  "crashReporterKey" : "8E4955EF-B107-0CB6-643D-06BB10BBA547",
  "wakeTime" : 2349,
  "sleepWakeUUID" : "5B89FCF5-94C7-4F97-B7A8-C64820B92F7B",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000000","rawCodes":[1,0],"type":"EXC_BAD_INSTRUCTION","signal":"SIGILL"},
  "termination" : {"flags":0,"code":4,"namespace":"SIGNAL","indicator":"Illegal instruction: 4","byProc":"exc handler","byPid":9856},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":118277,"threadState":{"r13":{"value":13},"rflags":{"value":515},"rax":{"value":37},"rosetta":{"tmp2":{"value":10208046286725156},"tmp1":{"value":4911734794889985221},"tmp0":{"value":4608831394}},"r14":{"value":4610357864,"symbolLocation":0,"symbol":"QByteArray::shared_null"},"rsi":{"value":13126921752},"r8":{"value":80},"rdx":{"value":8},"r10":{"value":140704539552616,"symbolLocation":24,"symbol":"__cxxabiv1::(anonymous namespace)::GlobalStatic<__cxxabiv1::(anonymous namespace)::LibcppMutex>::instance"},"r9":{"value":116},"r15":{"value":13126921752},"rbx":{"value":13126921752},"r11":{"value":4580028984,"symbolLocation":0,"symbol":"PyObject_GC_Del"},"rip":{"value":4608831394},"rbp":{"value":13126921648},"rsp":{"value":13126921440},"r12":{"value":13126921765},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":4609430107,"symbolLocation":6212,"symbol":"QUrl::setUrl(QString const&, QUrl::ParsingMode)::delims"}},"queue":"com.apple.main-thread","frames":[{"imageOffset":1097634,"symbol":"normalizeTypeInternal(char const*, char const*, bool, bool)","symbolLocation":792,"imageIndex":0},{"imageOffset":1086315,"symbol":"qNormalizeType(char*, int&, QByteArray&)","symbolLocation":146,"imageIndex":0},{"imageOffset":1085819,"symbol":"QMetaObject::normalizedType(char const*)","symbolLocation":211,"imageIndex":0},{"imageOffset":1101125,"symbol":"QMetaType::registerType(char const*, void (*)(void*), void* (*)(void const*))","symbolLocation":93,"imageIndex":0},{"imageOffset":9206,"symbol":"int qRegisterMetaType<PyQt_PyObject>(char const*, PyQt_PyObject*)","symbolLocation":47,"imageIndex":1},{"imageOffset":8787,"symbol":"qpycore_post_init(_object*)","symbolLocation":291,"imageIndex":1},{"imageOffset":653144,"symbol":"_PyImport_LoadDynamicModule","symbolLocation":140,"imageIndex":2},{"imageOffset":651759,"symbol":"imp_load_module","symbolLocation":243,"imageIndex":2},{"imageOffset":566586,"symbol":"PyEval_EvalFrameEx","symbolLocation":27019,"imageIndex":2},{"imageOffset":539071,"symbol":"PyEval_EvalCodeEx","symbolLocation":1618,"imageIndex":2},{"imageOffset":168072,"symbol":"function_call","symbolLocation":350,"imageIndex":2},{"imageOffset":44693,"symbol":"PyObject_Call","symbolLocation":99,"imageIndex":2},{"imageOffset":88935,"symbol":"instancemethod_call","symbolLocation":173,"imageIndex":2},{"imageOffset":44693,"symbol":"PyObject_Call","symbolLocation":99,"imageIndex":2},{"imageOffset":45091,"symbol":"call_function_tail","symbolLocation":72,"imageIndex":2},{"imageOffset":45596,"symbol":"PyObject_CallMethod","symbolLocation":231,"imageIndex":2},{"imageOffset":648276,"symbol":"import_submodule","symbolLocation":267,"imageIndex":2},{"imageOffset":647208,"symbol":"load_next","symbolLocation":280,"imageIndex":2},{"imageOffset":643648,"symbol":"PyImport_ImportModuleLevel","symbolLocation":1185,"imageIndex":2},{"imageOffset":520125,"symbol":"builtin___import__","symbolLocation":135,"imageIndex":2},{"imageOffset":44693,"symbol":"PyObject_Call","symbolLocation":99,"imageIndex":2},{"imageOffset":580395,"symbol":"PyEval_CallObjectWithKeywords","symbolLocation":165,"imageIndex":2},{"imageOffset":560355,"symbol":"PyEval_EvalFrameEx","symbolLocation":20788,"imageIndex":2},{"imageOffset":539071,"symbol":"PyEval_EvalCodeEx","symbolLocation":1618,"imageIndex":2},{"imageOffset":537447,"symbol":"PyEval_EvalCode","symbolLocation":48,"imageIndex":2},{"imageOffset":8393,"imageIndex":3},{"imageOffset":9882,"imageIndex":3},{"imageOffset":3780,"imageIndex":3}]},{"id":118336,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":18660,"imageIndex":4},{"imageOffset":71976,"imageIndex":4},{"imageOffset":77988,"imageIndex":4}]},{"id":118337,"frames":[{"imageOffset":141332,"imageIndex":4}]},{"id":118338,"frames":[{"imageOffset":141332,"imageIndex":4}]},{"id":118344,"frames":[{"imageOffset":141332,"imageIndex":4}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4607733760,
    "size" : 2584576,
    "uuid" : "2878eedc-9ce1-3944-9514-c858d0d82326",
    "path" : "\/Applications\/MOSAIC.app\/Contents\/MacOS\/QtCore",
    "name" : "QtCore"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4598697984,
    "size" : 1400832,
    "uuid" : "5b5264e0-aac9-338d-be10-a6843cf0893a",
    "path" : "\/Applications\/MOSAIC.app\/Contents\/MacOS\/PyQt4.QtCore.so",
    "name" : "PyQt4.QtCore.so"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4579270656,
    "size" : 1007616,
    "uuid" : "9a53817f-2101-3965-9831-1db81d851fba",
    "path" : "\/Applications\/MOSAIC.app\/Contents\/MacOS\/.Python",
    "name" : ".Python"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4374122496,
    "CFBundleShortVersionString" : "1.3.6",
    "CFBundleIdentifier" : "MOSAIC",
    "size" : 28672,
    "uuid" : "32ab4b3f-56df-3c81-b3ee-2215ac410955",
    "path" : "\/Applications\/MOSAIC.app\/Contents\/MacOS\/MOSAIC",
    "name" : "MOSAIC"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703125061632,
    "size" : 196608,
    "uuid" : "9f5d65be-d8d0-3979-bb05-e651a67e785c",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  }
],
  "sharedCache" : {
  "base" : 140703437946880,
  "size" : 15215640576,
  "uuid" : "b5084610-afe4-3485-bade-628c4468b057"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=882.7M resident=0K(0%) swapped_out_or_unallocated=882.7M(100%)\nWritable regions: Total=1.2G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.2G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nKernel Alloc Once                    8K        1 \nMALLOC                           206.1M       24 \nMALLOC guard page                   96K        4 \nMALLOC_MEDIUM (reserved)         480.0M        4         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nRosetta Arena                     4096K        2 \nRosetta Generic                   1008K      249 \nRosetta IndirectBranch             192K        2 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack                80K        8 \nRosetta Thread Context              80K        8 \nSTACK GUARD                         12K        3 \nStack                             9772K        4 \nStack Guard                       56.0M        1 \nVM_ALLOCATE                       17.3M       65 \n__DATA                            15.5M      273 \n__DATA_CONST                      8557K      144 \n__DATA_DIRTY                       310K       80 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       708.5M       44 \n__OBJC_RO                         81.6M        1 \n__OBJC_RW                         3120K        2 \n__TEXT                           174.2M      283 \n__UNICODE                          588K        1 \ndyld private memory               1024K        1 \nmapped file                        5.0G      400 \nshared memory                      800K       12 \nunshared pmap                     2288K        2 \n===========                     =======  ======= \nTOTAL                              7.3G     1622 \nTOTAL, minus reserved VM space     6.4G     1622 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "6194416dea7ed64a7812a429"
      },
      "deploymentId" : 240000322
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000162
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "61a69939b1c7c7620ce6e408"
      },
      "deploymentId" : 240000285
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000076
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro18,3, BootROM 7429.41.5, proc 10:8:2 processors, 16 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
Display: Color LCD, 3024 x 1964 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5
AirPort: Wi-Fi, wl0: Sep 24 2021 15:49:44 version 20.10.853.23.8.7.106 FWID 01-78e271b2
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB3.0 Hub
USB Device: USB 10/100/1000 LAN
USB Device: Elements SE 2623
USB Device: USB2.0 Hub
USB Device: USB 2.0 Hub
USB Device: USB Receiver
USB Device: USB Billboard Device
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by abalijepalli** [comment]
This is not something we have tested yet. I suspect not all the supporting libraries are available for the new Macs. I will leave this open as we get MOSAIC running on the M1 machines.

**Comment by LynneHomels** [comment]
> 

Thank you！But I can open it in the Parallels Desktop, which can run Windows on Mac. But the the software interface is not fully displayed.

**Comment by abalijepalli** [comment]
It appears that this is an old UI version that is not supported anymore. You can download the latest Windows 10 version MOSAIC from here: `https://github.com/usnistgov/mosaic/releases/download/v2.2/mosaic-x64-2.2+06ecb7a.zip`

When you double click it it should open a web browser and load the UI.

**Comment by LynneHomels** [comment]
Sorry, I cannot open the latest version, there may be something wrong.
![image](https://user-images.githubusercontent.com/63648453/146339284-d438c9f5-c227-4022-81ae-400565443357.png)

**Comment by LynneHomels** [comment]
The latest version could also not be opened in macOS.The UI could not be loaded correctly.
![image](https://user-images.githubusercontent.com/63648453/146341769-2f43ee8d-93e5-45cf-ae0b-ba905a67f3da.png)

**Comment by LynneHomels** [comment]
ok，thank you！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "usnistgov/mosaic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月26日(星期二) 晚上9:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [usnistgov/mosaic] Can not open in macOS 12.0.1 with apple m1 pro  (Issue #110)





 
This might be related to new functionality in macOS Monterey. It appears that AirPlay sharing now uses a port MOSAIC also needs. We may use a different port in a future update. For now a workaround is to turn off "Air Play Receiver" under Sharing in System Preferences, you should be able to use MOSAIC.
