### ISSUE TITLE
Cannot open mosaic in lenovo XiaoXinPro 14IHU 2021 Windows11

### ISSUE THREAD

**Issue by YAN-ui-dot** [usnistgov/mosaic#111]
Cannot open mosaic in lenovo XiaoXinPro 14IHU 2021 Windows11

**Comment by abalijepalli** [comment]
Can you provide some additional information? Is there an error message? We have not yet tested MOSAIC with Windows 11. Would it be possible too run on Windows 10 for now?

**Comment by YAN-ui-dot** [comment]
Thanks for your reply.
When I clicked on this software, it did not respond.there is no error message.It also crashed in my task manager .Windows 10 also cannot run it.

| |


|
|
***@***.***
|
签名由网易邮箱大师定制
On 12/15/2021 23:23，Arvind ***@***.***> wrote：

Can you provide some additional information? Is there an error message? We have not yet tested MOSAIC with Windows 11. Would it be possible too run on Windows 10 for now?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
