### ISSUE TITLE
Flask dependency issue

### ISSUE THREAD

**Issue by lmsteinberg** [usnistgov/mosaic#116]
Installing MOSAIC from source:
Flask 1.1.2 is requirement
During testing, I get the following errors after running:
python setup.py test

ERROR: Failure: ImportError (cannot import name 'escape' from 'jinja2' (/home/lms/enter/envs/mosaic/lib/python3.9/site-packages/jinja2/__init__.py))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lms/enter/envs/mosaic/lib/python3.9/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/lms/enter/envs/mosaic/lib/python3.9/site-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/home/lms/enter/envs/mosaic/lib/python3.9/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/lms/enter/envs/mosaic/lib/python3.9/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/lms/enter/envs/mosaic/lib/python3.9/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/home/lms/enter/envs/mosaic/lib/python3.9/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lms/mosaic/mosaicweb/__init__.py", line 1, in <module>
    from flask import Flask
  File "/home/lms/enter/envs/mosaic/lib/python3.9/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/home/lms/enter/envs/mosaic/lib/python3.9/site-packages/jinja2/__init__.py)

======================================================================
ERROR: tests.dependencyVersion_Test.DepencencyVersion_TestSuite.test_dependencyVersion('flask', '1.1.2')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lms/enter/envs/mosaic/lib/python3.9/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/lms/mosaic/tests/dependencyVersion_Test.py", line 5, in runTestCase
    module=__import__(dep)
  File "/home/lms/enter/envs/mosaic/lib/python3.9/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/home/lms/enter/envs/mosaic/lib/python3.9/site-packages/jinja2/__init__.py)

Name                                     Stmts   Miss  Cover
------------------------------------------------------------
mosaic/apps/SingleChannelAnalysis.py        48     34    29%
mosaic/apps/__init__.py                      0      0   100%
mosaic/mdio/__init__.py                      0      0   100%
mosaic/mdio/metaMDIO.py                     57     46    19%
mosaic/mdio/sqlite3MDIO.py                 221     87    61%
mosaic/partition/__init__.py                 0      0   100%
mosaic/partition/eventSegment.py            92     24    74%
mosaic/partition/metaEventPartition.py     268    136    49%
mosaic/process/adept.py                    156     56    64%
mosaic/process/adept2State.py              135     44    67%
mosaic/process/cusumPlus.py                180     46    74%
mosaic/process/metaEventProcessor.py        77     41    47%
mosaic/readGlobalSettings.py                14     14     0%
mosaic/settings.py                          48     26    46%
mosaic/trajio/ChimeraSettingsDict.py        70     34    51%
mosaic/trajio/binTrajIO.py                  49     19    61%
mosaic/trajio/chimeraTrajIO.py              45      2    96%
mosaic/trajio/metaTrajIO.py                219     74    66%
mosaic/trajio/qdf/qdf.py                   108     36    67%
mosaic/trajio/qdfTrajIO.py                  29     13    55%
mosaic/trajio/tsvTrajIO.py                  40     15    62%
------------------------------------------------------------
TOTAL                                     1856    747    60%
----------------------------------------------------------------------
Ran 182 tests in 35.822s

FAILED (errors=2)

**Comment by abalijepalli** [comment]
Are you able to run MOSAIC despite the testing errors? I am in the process of moving the unit testing away from nose which appears to be deprecated. I have seen issues where the tests fail recently but it doesn't impact MOSAIC running successfully. I'll mark this as a bug to be investigated further.

**Comment by lmsteinberg** [comment]
Hi, thanks for responding. I am an extreme novice so I have not been able to launch MOSAIC yet. I installed MOSAIC from source and although I can use setup.py to run tests, I don't think I have been able to properly build the application yet because when I try to launch I always get an error stating "file or folder cannot be found". So it is quite possible that MOSAIC can run just fine without this. 

I read that flask no longer supports the escape module in jinja2 and you can update the version of flask to one that does not need that. I did try changing this in the requirements.txt document but I got the same error so I assume I did not understand the dependencies for this.

I will keep working on building MOSAIC so that I can run it.

**Comment by abalijepalli** [comment]
I can help with that. It may be easier to email me (https://www.nist.gov/people/arvind-balijepalli) and we can troubleshoot the installation.
