### ISSUE TITLE
Windows 7: Event Viewer does not plot raw data

### ISSUE THREAD

**Issue by shadowk29** [usnistgov/mosaic#36]
When using the GUI in Windows 7 (from source on the devel-1.0 branch, not the pre-compiled GUI), the display includes the fits and calculated levels, but no raw data is plotted even if WriteEventTS==1.

The precompiled MOSAIC.exe version 1.2 appears to be unable to handle the results of runs from the devel-1.0 branch so I am unable to determine if the bug exists there as well.

**Comment by abalijepalli** [comment]
I was unable to reproduce the error on Windows. Here is the result of CUSUM analysis on Windows.

![cusum-windows](https://cloud.githubusercontent.com/assets/8433443/6233348/26bd4684-b6a0-11e4-8bf7-c6ad15f2c172.jpg)

I built a binary from the latest commit on devel-1.0. Could you check if the plot works with this version. If it does, it may point to issues with dependencies (pyqt or matplotlib).

https://drive.google.com/file/d/0ByixzyITmjSwcG9KMFB3Rk1TVms/view?usp=sharing

**Comment by shadowk29** [comment]
That does fix the issue. Must be a dependency problem as you say. I will update if I find out which one is the problem.

**Comment by shadowk29** [comment]
Updating to matplotlib-1.4.3 fixed the issue.
