### ISSUE TITLE
Second RC constant in stepResponseAnalysis can be negative

### ISSUE THREAD

**Issue by shadowk29** [usnistgov/mosaic#48]
Since the relaxation that RC constants need not be equal in stepResponseAnalysis, a file I recently analyzed (available on request) had several events with negative RC constant for the second one but reported normal processing status.

**Comment by forstater** [comment]
I've modified stepResponseAnalysis.py to mark these events as invalid and put a pull request in to merge this fix. When you get a chance, let me know if it works.

**Comment by abalijepalli** [comment]
Can you upload a small snippet of the file or a database that contains the event time-series? It would be useful to debug the cause of the negative RC constants.

**Comment by shadowk29** [comment]
DB and settings can be found here: https://www.dropbox.com/sh/zx3aiv5n8wbteny/AADV11dJmx9zHq0alB4uXqnca?dl=0

There are also a few negative residence times in that one. MOSAIC had a very hard time with that data set, which was odd for a number of reasons, so I am not sure that MOSAIC's model is appropriate for it to begin with.

**Comment by abalijepalli** [comment]
It appears that most of the events have extremely shallow blockades (i/i_0>0.95). It may just be that this is a pathological data set that may not be suited for MOSAIC as you alluded to previously. You could also try to link the RC constants. Just set "UnlinkRCConst" to 0 in the settings for stepResponse to see if that helps.

**Comment by shadowk29** [comment]
Yea, I don't think failure here points to any weakness inherent to MOSAIC, though unphysical time values need to be addressed somehow - the solution presented already is likely all that is needed to address the issue.
