### ISSUE TITLE
Feature request - ignore channel gating instead of aborting

### ISSUE THREAD

**Issue by shadowk29** [usnistgov/mosaic#50]
Currently I believe MOSAIC is set to abort analysis of the open channel current drifts past a defined threshold. Often it is the case that a clogged pore can be unclogged and the baseline would return to normal. It might be preferable to have mosaic continue processing data if the open channel current drifts significantly, but not look for events again until the current has returned to the initial state. This way you can ignore clogs and channel gating without missing out on analyzing data after the first clog, or having to chop the file into pieces to process it fully.

**Comment by abalijepalli** [comment]
You can override the drift check by setting "driftThreshold" to a large value (e.g. 999999.0) in the "eventSegment" settings. I'll leave this ticket open just in case changing that setting that doesn't fix the issue.

**Comment by shadowk29** [comment]
Ah, I think I misunderstood the description then. It will still continue analysis once the current has returned to an acceptable value? 

In the case where you allow MOSAIC to find the baseline (setting the relevent settings to -1), will it just ignore drift, or will it use the initial value to determine what is acceptable drift?

**Comment by abalijepalli** [comment]
Automatic baseline detection will estimate the drift at the start of the run and then detect changes from that value. If you have a gating event later in the run, the analysis should step over that if you set a driftThreshold that is larger than the gated step.

**Comment by shadowk29** [comment]
ah my mistake, ignore this then
