### ISSUE TITLE
export the data of resident time and blockade current 

### ISSUE THREAD

**Issue by HaiyanWang85** [usnistgov/mosaic#56]
Hi, I am a novice and learning Mosaic. Here is a question about the exporting data of resident time and blockade current. How to export the the acquisition data of resident time and blockade current by using Mosaic. Thank you.

**Comment by forstater** [comment]
Hi Haiyan,
   Lets sit down later this afternoon and I can show you.

Jacob

**Comment by abalijepalli** [comment]
We can add an export to CSV function in the MOSAIC gui to allow users to export data out of the SQLite database.

**Comment by forstater** [comment]
Great Idea!

**Comment by HaiyanWang85** [comment]
Hi Jacob,
    OK, Thank you. I will look you after lunch.

Haiyan

2015-08-05 10:52 GMT-04:00 forstater <notifications@github.com>:

**Comment by shadowk29** [comment]
export to csv would be very useful
