### ISSUE TITLE
(Ubuntu)IndexError: list index out of range

### ISSUE THREAD

**Issue by ppsaf** [usnistgov/mosaic#58]
ISSUE:In ubuntu ,we analysis the .abf. After activating the "start analysis“ button,the terminal will show the next error,and stop analysis.The software is source Installation.
![2015-08-18 21 30 55](https://cloud.githubusercontent.com/assets/13852050/9331205/aa89a3c4-45f0-11e5-841a-28e3a4b3a62a.png)

**Comment by abalijepalli** [comment]
I am not able to reproduce this issue using v1.2 on Ubuntu. Can you post a snippet of the data?

**Comment by ppsaf** [comment]
I was also using v1.2 on ubuntu 14.04.The file format is .abf.
![20150819091442](https://cloud.githubusercontent.com/assets/13852050/9346901/f51528d2-4654-11e5-950b-97f166958a11.png)
Otherwhise,on windows we can start the caculation.The stepResponseAnalysis is correct,but the result of the MultistateAnalysis in detabase is messy displlay
![20150819091720](https://cloud.githubusercontent.com/assets/13852050/9346902/f51bc412-4654-11e5-83a4-25c4070cfaa5.jpg)



.

**Comment by abalijepalli** [comment]
It may be easier if we could look at the sqlite file generated by MOSAIC. It appears that stepResponse was not selected during the analysis for some reason. 

It would be easier to debug if you  join the MOSAIC mailing list (https://usnistgov.github.io/mosaic/html/doc/mailingList.html) and send an email. Reference this issue and also include the SQLITE database in your email.
