### ISSUE TITLE
Little Blips in Timeseries of fitted events

### ISSUE THREAD

**Issue by Silberbaer** [usnistgov/mosaic#91]
When plotting the timeseries column from the database file for successfully fitted events, there appear to be a small blip on the rising flank of events (see attached pictures). It seems to be fairly consistent and appears more often on super short events but is also visible on longer ones.

![event1](https://cloud.githubusercontent.com/assets/17032975/22074071/294af0ba-dd75-11e6-96e9-34a0e72e064f.png)
![event2](https://cloud.githubusercontent.com/assets/17032975/22074083/31bc70c0-dd75-11e6-8168-dabf683c9b75.png)

**Comment by abalijepalli** [comment]
Looks like pre-event baseline has a redundant data point. Commit 58cbed0c44e7b306cc4876a67411968c8833ba4e should fix this. I'll leave this issue open for now.
