### ISSUE TITLE
Chimera Files are not read in correct order

### ISSUE THREAD

**Issue by Silberbaer** [usnistgov/mosaic#92]
When loading up data files generated by the Chimera VC100, the files are not loaded in the same order as they were generated. This messes up the time ordering in the overall current trace.

**Comment by shadowk29** [comment]
Possible solution here: http://stackoverflow.com/questions/6773584/how-is-pythons-glob-glob-ordered
```
import os
sorted(glob.glob(filter), key=os.path.getmtime)
```

**Comment by abalijepalli** [comment]
Should we sort by mod time or filename, i.e. assume there is some chronological ordering of filenames as they are generated? Would relying on mod time cause issues if the files were moved on some OSes?

**Comment by shadowk29** [comment]
You're probably correct that we should sort by name. The default format for chimera files is [basename]_yyyymmdd_hhmmss.log. If sorting by name matches chronological order that will work (it should, I think)

**Comment by abalijepalli** [comment]
Commit 877486d2d78cb6c1b885d72011cc5fdf932cdc71 adds a lexical sort to the globbed files. Let me know if that fixes it.
