### ISSUE TITLE
Timeseries EventPadding Noise is cut off after the event

### ISSUE THREAD

**Issue by Silberbaer** [usnistgov/mosaic#93]
When plotting timeseries for correctly fitted events the baseline padding after the event shows lower noise than before the event. Is not affected by value of event padding and cannot be seen in the raw data.

![image](https://cloud.githubusercontent.com/assets/17032975/23081562/68686bf4-f523-11e6-8ce2-5c1d808432c9.png)
![image](https://cloud.githubusercontent.com/assets/17032975/23081576/7a37d18a-f523-11e6-9847-f5c04313c541.png)

**Comment by abalijepalli** [comment]
The post event pad is filtered to remove adjacent events that may throw off the fit. The mean of the baseline current remains unchanged.

**Comment by Silberbaer** [comment]
Is there a way to have that removed from the timeseries output and instead plot the real raw trace of the event?

**Comment by abalijepalli** [comment]
The post event padding is filtered on line _181_ in `partition/eventSegment.py`. You could turn off the filtering there. However, it would be better to expose that functionality as a switch through the settings.
