### ISSUE TITLE
Unknown Error for every detected event when updating to newer version of numpy

### ISSUE THREAD

**Issue by Silberbaer** [usnistgov/mosaic#97]
After updating to the newest version of numpy (1.14.3) every event in the output file was flagged with 'eUnknownError_init'. Earlier versions of numpy (1.11.3) gave the following deprecation warning:

.....\cusumPlus.py:306: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  currentlevels = [np.average(edat[edges[i]+self.MinLength:edges[i+1]]) for i in range(self.nStates)] #detect current levels during detected sub-events

In the newer version of numpy this warning gives an error instead and events will not be fit at all.

**Comment by abalijepalli** [comment]
@Silberbaer and @shadowk29 please review commit e47e4ea5751aa3ec1d608af633f84647449fd0fb to ensure it addresses the issue.

**Comment by shadowk29** [comment]
Sounds like this works, thank you
